services:
  redis:
    image: redis:alpine
    restart: unless-stopped
    command: redis-server --save 30 1 --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - searxng-network

  searxng:
    image: searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "8888:8080"
    environment:
      - SEARXNG_BASE_URL=http://localhost:8888/
      - SEARXNG_SECRET=${SEARXNG_SECRET}
    volumes:
      - searxng_data:/etc/searxng
    depends_on:
      - redis
    networks:
      - searxng-network

volumes:
  redis_data:
  searxng_data:

networks:
  searxng-network:
    driver: bridge
