services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports:
      - "8096:8096"      # HTTP web interface
      - "8920:8920"      # HTTPS web interface (optional)
      - "7359:7359/udp"  # Service discovery
      - "1900:1900/udp"  # Service discovery
    environment:
      - TZ=${TIMEZONE}
    volumes:
      - jellyfin_config:/config
      - jellyfin_cache:/cache
      - ${MEDIA_PATH}:/media:ro  # Read-only media directory
    # Uncomment for hardware transcoding (Intel QuickSync)
    # devices:
    #   - /dev/dri:/dev/dri
    # group_add:
    #   - "109"  # render group

volumes:
  jellyfin_config:
  jellyfin_cache:
