name: Lint and Format

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: '.'
          severity: warning
          ignore_paths: '.git'

  shfmt:
    name: Shell Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install shfmt
        run: |
          wget -qO /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.8.0/shfmt_v3.8.0_linux_amd64
          chmod +x /usr/local/bin/shfmt

      - name: Check shell script formatting
        run: |
          shfmt -d -i 4 -ci -bn .

  hadolint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Find Dockerfiles
        id: dockerfiles
        run: |
          if find services -name "Dockerfile" -o -name "Dockerfile.*" | grep -q .; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Run hadolint
        if: steps.dockerfiles.outputs.found == 'true'
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "services/*/Dockerfile*"
          recursive: true
          failure-threshold: warning

  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install yamllint
        run: pip install yamllint

      - name: Create yamllint config
        run: |
          cat > .yamllint <<EOF
          extends: default
          rules:
            line-length:
              max: 120
            indentation:
              spaces: 2
            comments:
              min-spaces-from-content: 1
          EOF

      - name: Run yamllint
        run: yamllint -f parsable services/*/docker-compose.yml .github/
